version: '3.7'
services:
  fastapi-test: &box
    build:
      context: ./
    volumes:
      - ./:/opt/fastapi-test/
    ports:
      - 5000:5000
  app-dev:
    <<: *box
    command: uvicorn --reload --workers 1 --host 0.0.0.0 --port 5000 app.app:app
  app-prod:
    <<: *box
    command: uvicorn --workers 2 --host 0.0.0.0 --port 5000 app.app:app
